# **Deep Learning Tutorial Course**
## **Day 2: Linear Algebra and Matrices**

### **Overview**
Linear Algebra is the foundation of many deep learning algorithms. Understanding matrix operations, tensors, and their applications in forward and backward propagation is essential for building and optimizing neural networks.

---

### **What You Will Learn**
1. Basics of tensors
2. Matrix operations (dot product, transpose, determinant)
3. Importance of tensors in forward and backpropagation
4. Implementing matrix multiplication and basic tensor operations using NumPy

---

### **Why Linear Algebra is Important in Deep Learning**
- **Vectorized Operations**: Efficient computation using GPUs requires operations on tensors (generalized matrices).
- **Representation of Data**: Images, texts, and even sounds can be represented as matrices or tensors.
- **Optimization**: Gradients, which are used in backpropagation, are computed using matrix operations.

---

## **1. Basics of Tensors**
Tensors are generalizations of matrices to higher dimensions:
- A **scalar** is a 0D tensor (single number).
- A **vector** is a 1D tensor (array of numbers).
- A **matrix** is a 2D tensor (table of numbers).
- Higher-dimensional tensors (3D, 4D, etc.) are used for complex data like images and video.


In [1]:
import numpy as np

# Scalars
scalar = 5
print(f"Scalar: {scalar}")

# Vectors
vector = np.array([1, 2, 3])
print(f"Vector: {vector}")

# Matrices
matrix = np.array([[1, 2], [3, 4]])
print(f"Matrix:\n{matrix}")

# 3D Tensor
tensor_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(f"3D Tensor:\n{tensor_3d}")

Scalar: 5
Vector: [1 2 3]
Matrix:
[[1 2]
 [3 4]]
3D Tensor:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


a) Transpose of a Matrix

The transpose of a matrix flips its rows and columns.

In [2]:
matrix = np.array([[1, 2], [3, 4]])
transpose = matrix.T
print(f"Original Matrix:\n{matrix}")
print(f"Transpose:\n{transpose}")


Original Matrix:
[[1 2]
 [3 4]]
Transpose:
[[1 3]
 [2 4]]


b) Dot Product

The dot product is a key operation in deep learning, used in operations like calculating weights and biases.

In [3]:
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])
dot_product = np.dot(matrix_a, matrix_b)
print(f"Matrix A:\n{matrix_a}")
print(f"Matrix B:\n{matrix_b}")
print(f"Dot Product:\n{dot_product}")


Matrix A:
[[1 2]
 [3 4]]
Matrix B:
[[5 6]
 [7 8]]
Dot Product:
[[19 22]
 [43 50]]


c) Determinant of a Matrix

The determinant is useful in checking if a matrix is invertible.

In [4]:
from numpy.linalg import det

matrix = np.array([[1, 2], [3, 4]])
determinant = det(matrix)
print(f"Matrix:\n{matrix}")
print(f"Determinant: {determinant}")


Matrix:
[[1 2]
 [3 4]]
Determinant: -2.0000000000000004


3. Applications in Deep Learning

- Forward Propagation
Activations are computed using weighted sums of inputs.
Weighted sums are represented as dot products of matrices.
- Backpropagation
Gradients are computed using matrix derivatives.

Example: Forward Propagation in a Simple Neural Network

In [5]:
# Input features
inputs = np.array([1, 2])

# Weights for 2 neurons
weights = np.array([[0.1, 0.2], [0.3, 0.4]])

# Biases
biases = np.array([0.5, 0.6])

# Weighted sum (dot product)
weighted_sum = np.dot(inputs, weights) + biases
print(f"Inputs: {inputs}")
print(f"Weights:\n{weights}")
print(f"Biases: {biases}")
print(f"Weighted Sum (Forward Propagation): {weighted_sum}")


Inputs: [1 2]
Weights:
[[0.1 0.2]
 [0.3 0.4]]
Biases: [0.5 0.6]
Weighted Sum (Forward Propagation): [1.2 1.6]


4. Implementing Basic Tensor Operations with NumPy

Element-wise Operations

In [6]:
matrix = np.array([[1, 2], [3, 4]])
print(f"Original Matrix:\n{matrix}")
print(f"Matrix + 1:\n{matrix + 1}")
print(f"Matrix * 2:\n{matrix * 2}")


Original Matrix:
[[1 2]
 [3 4]]
Matrix + 1:
[[2 3]
 [4 5]]
Matrix * 2:
[[2 4]
 [6 8]]


Broadcasting

Broadcasting is a powerful feature of NumPy that enables arithmetic operations on tensors of different shapes.

In [7]:
matrix = np.array([[1, 2], [3, 4]])
vector = np.array([1, 2])
broadcasted_sum = matrix + vector
print(f"Matrix:\n{matrix}")
print(f"Vector: {vector}")
print(f"Broadcasted Sum:\n{broadcasted_sum}")


Matrix:
[[1 2]
 [3 4]]
Vector: [1 2]
Broadcasted Sum:
[[2 4]
 [4 6]]


5. Advantages and Disadvantages
- Advantages

Vectorization: Matrix operations speed up computations, especially on GPUs.

Representation: Any data type can be converted into tensors.
- Disadvantages

Complexity: Requires a strong foundation in linear algebra.

Debugging: Errors in dimensions (shapes) can be hard to debug.


Create a 2D matrix and calculate its transpose.

Multiply two matrices of size (2x3) and (3x2).

In [8]:
# Example: Matrix Multiplication
matrix_a = np.random.randint(1, 10, size=(2, 3))
matrix_b = np.random.randint(1, 10, size=(3, 2))
result = np.dot(matrix_a, matrix_b)
print(f"Matrix A:\n{matrix_a}")
print(f"Matrix B:\n{matrix_b}")
print(f"Result of Multiplication:\n{result}")


Matrix A:
[[8 8 3]
 [2 2 5]]
Matrix B:
[[1 5]
 [5 1]
 [1 1]]
Result of Multiplication:
[[51 51]
 [17 17]]
